version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.0
    volumes:
      - /jekyll:/srv/jekyll
    ports:
      - "4000:4000"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.jekyll.rule=Host(`blog.rikvoorhaar.com`)"
    networks:
      - internal


    command: jekyll serve
    environment:
      - JEKYLL_VERSION=4.0
      - JEKYLL_ENV=production
    
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /jekyll/_site:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=blog.rikvoorhaar.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`blog.rikvoorhaar.com`)"
      # - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    depends_on:
      - jekyll
    networks:
      - internal

  fluentd:
    image: fluent/fluentd
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
      - ./fluentd-plugins:/fluentd/plugins
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - internal
  
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=logs
    networks:
      - internal

networks:
  web:
    external: true
  internal: