version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.0
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --watch --drafts --incremental --livereload
    environment:
      - JEKYLL_VERSION=4.0