# Docker compose for running the website locally

version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    volumes:
      - ./:/srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    command: jekyll serve --livereload --force_polling # --host=0.0.0.0
    environment:
      - JEKYLL_VERSION=4.0